class spec_loadout {
    tag = "Spec";
    class init {
        file="spec_loadout";
        class addContainer {};
        class addItemToContainer {};
        class initLoadoutLists {};
        class loadout_aaf {};
        class loadout_bw_tropentarn {};
        class loadout_bw_flecktarn {};
        class loadout_csat {};
        class loadout_csat_tropentarn {};
        class loadout_cup_ussocom {};
        class loadout_korea {};
        class loadout_nato {};
        class loadout_nato_tropentarn {};
        class loadout_norway_wood {};
        class loadout_norway_desert {};
        class loadout_police {};
        class loadout_rus_flora {};
        class loadout_rus_flora_alt {};
        class loadout_syndicat {};
        class loadout_uk {};
        class loadout_uk_winter {};
        class loadout_ukraine {};
        class loadout_usarmy {};
        class loadout_usmc {};
        class loadout_ussocom {};
        class loadoutBox {};
        class loadoutFaction {};
        class loadoutParseUnitAndType {};
        class loadoutStandardEquipment {};
        class units_init { postInit = 1; };
    };
};
