//--- Spec_crateNaming
#define IDC_SPEC_CRATENAMING_DIALOGID 5200
#define IDC_SPEC_CRATENAMING_EDITBOX 13691
#define IDC_SPEC_CRATENAMING_BUTTON_RESET 13891
#define IDC_SPEC_CRATENAMING_BUTTON_OK 14891
#define IDC_SPEC_CRATENAMING_BUTTON_CANCEL 14991

#define IDC_OK 1
#define IDC_CANCEL 2

#define SPEC_CRATENAMING_CRATE_VAR "spec_crateNaming_crate"